export interface UserDataRegister {
  firstName: string;
  lastName: string;
  email: string;
}

// Generated by https://quicktype.io

export interface UserDataResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  registerDate: string;
  updatedDate: string;
}
